### ISSUE TITLE
set temporary max and min until they are overridden

### ISSUE THREAD

**Issue by nervusvagus** [RobTillaart/MINMAX#8]
would it be possible to set temporary max and min values for the beginning until we receive values higher and lower?

**Comment by RobTillaart** [comment]
Thanks for the issue,

Technically this is possible, the easiest way is probably to add the MIN and MAX you want.
You can give it a try.

As I'm quite busy I can come back to it tomorrow.

**Comment by nervusvagus** [comment]
:) thank you . otally overlooked that yes i believe 
mm.add(0); // Temporary minimum
mm.add(2000); // Temporary maximum
is the ideal way.

**Comment by RobTillaart** [comment]
If that works for you you may close the issue.

**Comment by RobTillaart** [comment]
Question might be a feature. Some thoughts:
- proposed solution does not work nice with **autoreset()**
- proposed solution generates two call back calls if defined.
- proposed solution needs to be applied after every **reset()**


Ideas for improvement 
- defines for reset to reset to
- parameterize **reset(min, max)**
- new function **setRestDefaults(min max)** or named **setInitialRange(min max)**
- functions **setMin(val) setMax(val)**
- needs to be backwards compatible
- needs to be runtime adjustable

**Comment by nervusvagus** [comment]
If i understand right, the bool flag would set the min max values as base and ceiling values. I think there might be cases where we need both an initial starting min max and a ceiling value. 

In my case I output the movement / speed from a childrens swing, swing seat with accelerometer, into ws2812b lights and since I dont have initial speed values set the lights start with flickering. The starting min max would help with this. the ceiling value setting might help in cases where theres a shake on swing seat and acceleration or speed reads in extreme values.

Im trying to measure tilt and I set starting min max values however doesnt seem to work in 0.2.2 with minmaxPitch.setResetDefaults(-50.00, 50.00); yet.

**Comment by RobTillaart** [comment]
Thank you for describing your project. Think the children (and parents) love it.
Your project is definitely not a project I would have thought about when developing the library. 
It is always amazing to hear what people create with some library.
Thanks for sharing!
